# Generated by Django 5.0.1 on 2024-02-23 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_owner', models.CharField(max_length=200, verbose_name='владелец блога')),
                ('blog_owner_description', models.TextField(verbose_name='о себе')),
                ('blog_car', models.CharField(max_length=100, verbose_name='автомобиль')),
                ('registration_date', models.DateTimeField(verbose_name='дата создания')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=200, verbose_name='название поста')),
                ('post_text', models.TextField(verbose_name='текст поста')),
                ('posted_date', models.DateTimeField(verbose_name='время записи')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.blog')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=200, verbose_name='имя автора')),
                ('comment_text', models.TextField(verbose_name='текст комментария')),
                ('comment_date', models.DateTimeField(verbose_name='время комментария')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.post')),
            ],
        ),
    ]
